project:
  type: website

website:
  title: "Chantan NEW Quarto Website"
  navbar:
    background: success
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - text: EPPS 6356
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - href: assignment4.qmd
            text: Assignment 4
          - href: assignment5.qmd
            text: Assignment 5
          - href: assignment6.qmd
            text: Assignment 6
          - href: assignment7.qmd
            text: Assignment 7
          - href: assignment8.qmd
            text: Assignment 8

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: source

